### ISSUE TITLE
U-Boot

### ISSUE THREAD

**Issue by zeidlermicha** [kenbell/tamago-example-pi2#1]
Hey,
I tried to get this example running. I compiled against your version of tamago with branches "rpi_support" as well as "working". Also i compiled u-boot using this repo: https://github.com/swarren/u-boot. My SD-Card contains the following files:

- boot.scr (unedited)
- config.txt (unedited)
- example-pi-2
- u-boot-pi2.bin

Connecting UART on ports 6 to 10 I don't get any output. Also LEDs are not blinking.
Could you provide the u-boot you used so I can rule out any errors from my compiled version?
Also thank you for your effort in implementing rpi support!

**Comment by kenbell** [comment]
I've been using u-boot from here: git://git.denx.de/u-boot.git

If you're seeing nothing, it might be there's no Pi bootcode on the card - the Pi needs this to bootstrap.  You'll at least need  bootcode.bin and start.elf.  The first lines output to the UART should look something like this, output by the Pi bootstrap code:

```
Raspberry Pi Bootcode

Read File: config.txt, 211

Read File: start.elf, 2884708 (bytes)

```

**Comment by zeidlermicha** [comment]
Indeed I was missing bootcode. Now at least im getting some output.
